name: Deploy

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  
jobs:
  deploy:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        
        - name: Set env
          run: echo "RELEASE_VERSION=${${{ inputs.username }}#refs/*/}" >> $GITHUB_ENV
      
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Pull docker image
          run: /usr/bin/docker pull ghcr.io/vincentvibe3/emergencyfood:${{ env.RELEASE_VERSION }}
        
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy -i ghcr.io/vincentvibe3/emergencyfood:${{ env.RELEASE_VERSION }}

        - name: Status webhook
          uses: sarisia/actions-status-discord@v1
          if: always()
          with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            title: "Deploy workflow"
            username: GitHub Actions
