name: Release

on:
  push:
    tags:
      - 'v.*'
  pull_request:
    tags:
      - 'v.*'
  workflow_dispatch:

jobs:
  build:
      uses: ./.github/workflows/Build.yaml
      secrets: inherit
  
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: jar
      
      - name: Move jar
        shell: bash
        run: mkdir -p ./build/libs && mv ./Emergencyfood*.jar ./build/libs
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build docker image
        run: /usr/bin/docker build . -t ghcr.io/vincentvibe3/emergencyfood:${{ env.RELEASE_VERSION }}
        
      - name: Push docker image
        run: /usr/bin/docker push ghcr.io/vincentvibe3/emergencyfood:${{ env.RELEASE_VERSION }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/Emergencyfood*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Status webhook
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Release workflow"
          username: GitHub Actions
  deploy:
      needs: release
      uses: ./.github/workflows/Deploy.yml
      with:
        ref: ${{ github.ref }}
      secrets: inherit
